name: Anixart Simple Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y default-jre zipalign wget unzip

      - name: Загрузка apktool.jar
        run: |
          wget -O apktool.jar https://raw.githubusercontent.com/iBotPeaches/Apktool/master/brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar

      - name: Скачивание APK
        run: wget -O orig.apk https://dl.anixart-app.com/anixart.apk

      - name: Распаковка APK
        run: java -jar apktool.jar d orig.apk -o anixart

      - name: Редактирование smali
        run: |
          sed -i '/\.method public final D()Z/,/\.end method/c\
.method public final D()Z\n    .locals 0\n\n    const/4 p0, 0x1\n\n    return p0\n.end method' \
anixart/smali_classes2/com/swiftsoft/anixartd/Prefs.smali

      - name: Сборка APK
        run: |
          java -jar apktool.jar b anixart -o build.apk
          zipalign -v 4 build.apk build_aligned.apk

      - name: Подпись APK
        run: |
          echo "dinaco" > keystore.pass
          apksigner sign --ks dinaco --ks-pass file:keystore.pass --key-pass file:keystore.pass \
--v1-signing-enabled true --v2-signing-enabled true build_aligned.apk

      - name: Проверка APK
        run: apksigner verify build_aligned.apk

      - name: Загрузка артефакта
        uses: actions/upload-artifact@v3
        with:
          name: anixart.apk
          path: build_aligned.apk
